version: "3.8"
services:
  web:
    build: ./app
    command: 114703361824.dkr.ecr.us-east-1.amazonaws.com/django_docker_aws:django_docker_aws_web
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
  nginx:
    build: ./nginx
    volumes:
      - 114703361824.dkr.ecr.us-east-1.amazonaws.com/django_docker_aws:django_docker_aws_nginx
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume:


